version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: colibri
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongodata:/data/db]

  gateway:
    build: ./apigateway
    environment:
      ROUTES_MAP: |
        /auth=http://auth:3000
        /users=http://users-profiles:3000
        /routes=http://routes-search:3000
        /reservations=http://reservations:3000
        /wallet=http://wallet-conciliation:3000
        /driver-day=http://driverday:3000
        /notifications=http://notifications:3000
    ports: ["8080:8080"]
    depends_on: [auth, users-profiles, routes-search, reservations, wallet-conciliation, driverday, notifications]

  nginx:
    build: ./nginx
    ports: ["80:80"]
    depends_on: [gateway]

  auth:
    build: ./microservices/auth
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/colibri
    depends_on: [postgres]
  users-profiles:
    build: ./microservices/users-profiles
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/colibri
    depends_on: [postgres]
  routes-search:
    build: ./microservices/routes-search
    environment:
      MONGO_URL: mongodb://mongo:27017/colibri
    depends_on: [mongo]
  reservations:
    build: ./microservices/reservations
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/colibri
    depends_on: [postgres]
  wallet-conciliation:
    build: ./microservices/wallet-conciliation
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/colibri
    depends_on: [postgres]
  driverday:
    build: ./microservices/driverday
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/colibri
    depends_on: [postgres]
  notifications:
    build: ./microservices/notifications

volumes:
  pgdata:
  mongodata:
